### ISSUE TITLE
Does not compile with `phf` version v0.9.1

### ISSUE THREAD

**Issue by erikjohnston** [sfackler/rust-postgres#817]
The `tokio-postgres` specifies a dependency on "0.9". Trying to compile with updated deps gives:

```
error[E0433]: failed to resolve: could not find `Slice` in `phf`
    --> tokio-postgres/src/error/sqlstate.rs:1344:19
     |
1344 |     disps: ::phf::Slice::Static(&[
     |                   ^^^^^ could not find `Slice` in `phf`

error[E0433]: failed to resolve: could not find `Slice` in `phf`
    --> tokio-postgres/src/error/sqlstate.rs:1398:21
     |
1398 |     entries: ::phf::Slice::Static(&[
     |                     ^^^^^ could not find `Slice` in `phf`

```

Looks like `phf::Slice` was removed between 0.9.0 and 0.9.1, as it wasn't considered part of the public API: https://github.com/rust-phf/rust-phf/commit/99d353390f8124a283da9202fd4d163e68bc1949

Link to usage: https://github.com/sfackler/rust-postgres/blob/master/tokio-postgres/src/error/sqlstate.rs#L1344 and https://github.com/sfackler/rust-postgres/blob/master/tokio-postgres/src/error/sqlstate.rs#L1398

**Comment by sfackler** [comment]
The phf folks have yanked that version so we should be good now.
