### ISSUE TITLE
 the trait `postgres::types::ToSql` is not implemented for `uuid::Uuid`

### ISSUE THREAD

**Issue by zhaohansprt** [sfackler/rust-postgres#364]
[dependencies]
r2d2 = "0.8"
r2d2_postgres = "0.14"   # newer version, uses postgres 0.12
postgres = { version = "0.15", features = ["with-uuid"] }
parking_lot = "0.5"
uuid = {version ="0.6.5",features = ["serde", "v4"]}

error[E0277]: the trait bound `uuid::Uuid: postgres::types::ToSql` is not satisfied
  --> src/main.rs:66:85
   |
66 |         let conn4=&conn3.query("SELECT version FROM cbox.version WHERE botID=$1", &[&my_uuid]).unwrap() ;
   |                                                                                     ^^^^^^^^ the trait `postgres::types::ToSql` is not implemented for `uuid::Uuid`
   |
   = note: required for the cast to the object type `dyn postgres::types::ToSql`

**Comment by sfackler** [comment]
postgres 0.15 works with uuid 0.5, not 0.6.

**Comment by zhaohansprt** [comment]
great  solved!
