### ISSUE TITLE
Working with `uuid` and `Jsonb`

### ISSUE THREAD

**Issue by hajsf** [sfackler/rust-postgres#476]
In PgAdmin, I was able to execute the below:
```sql
CREATE TABLE public.devices
(
    id uuid,
    data jsonb
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.devices
    OWNER to postgres;

INSERT INTO devices (
id, 
"user"
) VALUES (
'a0eebc999c0b4ef8bb6d6bb9bd380a11',
'{"name": "Hasan", 
"genres": ["Fiction", "Thriller", "Horror"],
"new": true}');

select id from devices where data @> '{"name":"Hasan"}';
select id from devices where data->>'name' = 'Hasan' ;
```

Trying to do same with Rust, so I wrote the below:

`Cargo.toml`:
```toml
[dependencies]
rocket = "0.4.2"
ws = "0.9.0"
serde = "1.0.99"
serde_json = "1.0.40"
serde_derive = "1.0.99"
lazy_static = "1.4.0"
uuid = "0.7"
postgres = { version = "0.15.2", features = ["with-chrono", "with-uuid", "with-serde_json"] }

[dependencies.rocket_contrib]
version = "0.4.2"
default-features = false
features = ["serve","tera_templates", "json", "postgres_pool"]
```
The rust code is:
```rust
#![feature(proc_macro_hygiene, decl_macro)]
#![feature(const_vec_new)]

#[macro_use] extern crate rocket;
use rocket::config::{Config, Environment};
#[macro_use] extern crate rocket_contrib;
#[macro_use] extern crate lazy_static;
use rocket_contrib::databases::postgres;

use uuid::Uuid;
mod connection;

fn main() {

    use connection::conn;

    let devices = &conn().query("select id, data from devices where data->>'name' = $1",
        &[&"Hasan"]).
    expect("Could'n read table");
   let d_id: Uuid = devices.get(0).get(0);
   let d_user: Json<User> = devices.get(0).get(1);
}
```

Where `mode connection` is:
```rust
use postgres::{Connection, TlsMode};

pub fn conn() -> Connection {
    let url = "PostgreSQL11://user:pswd@localhost:5432/db";
    let conn = Connection::connect( url, TlsMode::None).
    expect("Couln't connect to DB");
    conn
}
```

But I'm getting the below errors:
```bash
error[E0277]: the trait bound `uuid::Uuid: rocket_contrib::databases::postgres::types::FromSql` is not satisfied
   --> src\main.rs:152:33
    |
152 | let d_id: Uuid = devices.get(0).get(0);
    |                                 ^^^ the trait `rocket_contrib::databases::postgres::types::FromSql` is not implemented for `uuid::Uuid`

error[E0277]: the trait bound `rocket_contrib::json::Json<User>: rocket_contrib::databases::postgres::types::FromSql` is not satisfied
   --> src\main.rs:153:41
    |
153 | let d_user: Json<User> = devices.get(0).get(1);
    |                                         ^^^ the trait `rocket_contrib::databases::postgres::types::FromSql` is not implemented for `rocket_contrib::json::Json<User>`

error: aborting due to 2 previous errors
```

**UPDATE**

The `jsonb` worked by doing:
```rust
use serde_json::Value as JSON;

let devices = &conn().query("select id, data from devices where data->>'name' = $1",
        &[&"Hasan"])

let d_user: JSON = devices.get(0).get(1);
```

Still could not solve the `uuid` issue?

**UPDATE 2**
The UUID worked with `uuid = "0.5"` but failed to work with `uuid = "0.7"`

**Comment by sfackler** [comment]
> The UUID worked with `uuid = "0.5"` but failed to work with `uuid = "0.7"`

Yes, that's the version of the uuid crate that postgres 0.15 supports.

**Comment by Venryx** [comment]
For other lost Googlers, who are using `async-graphql` (and want an `ID` instance from the field), this is what worked for me:
```
let id: ID = ID::from(&row.get::<_, String>("id"))
```
